### PR TITLE
Method for clearing the drawing

### PR DESCRIPTION
**Pull request by johandweber**
I have added a method clear to the drawing class that 
removes all shapes with the exception of the background.

This is done by saving the background color of the image, than de-allocating
the array this shapes and re-adding the background.

Note: I am not sure whether this approach is method is completely memory-save,
as it acts on an array of polymorphic objects.  
It is likely to be OK as log a s the "child" shapes  have a fixed size, but it might be insufficient
if newer ones (polylines ect. ) contain allocatable/pointer elements. 

@perazz

### CODE REVIEW

**Review by perazz — APPROVED** [review]
Looks good to me, thank you @johandweber! In the future, we may want to think whether it is possible to “spare” some allocations I.e. clear the drawing by only setting “n shapes=0” without touching the storage. However, that is not going to be relevant unless one has an interactive figure that keeps changing, so definitely not an issue rn.

**Comment by johandweber** [comment]
Thank you.

Maybe  a "Null-Operation" would be useful.

I think that updating an existing draweing in non-interactive applications like video creation
(I do not think that video creation is far off the scope of this library. At the
end a video is just a series of images and while we will not write a MPEG codec
in pure Fortran in the near future, it is always possible to write a series of image
files or a stream of data in a pipe and let external tools like FFMPEG do the rest. )

**Review by AnonMiraj — APPROVED** [review]
Looks good to me. Like you said, handling some shapes like polyline, etc., will be tricky. However, for now, I think it will be fine.

**Comment by AnonMiraj** [comment]
Why did you close it?
 I was about to merge it after fixing the conflict.

**Pull request closed without merging**
